# Site settings
title: "Amanda & Matthew"
email: huastonewedding@gmail.com
url: https://msto.github.io/
description: "March 24, 2018 | Cambridge, Massachusetts"

# Color settings (hex-codes without the leading hash-tag)
color:
  # primary-dark: '#196980'
  # primary-dark: '#10193c'
  primary-dark: '#213c61'
  primary-light: '#fff'
  links: '#d8dcd6'

# Footer settings
footer: Amanda and Matt

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: https://twitter.com/SBootstrap

site-map:
    menu:
        - home
        - details
        - travel
        - registry
    home:
        title: home
    details:
        title: Ceremony & Reception
        sections:
            - Ceremony & Reception
            - FAQ
    travel:
        title: Travel & Accomodations
        sections: 
            - Venue
            - Hotels
            - Airport
            - Public transportation
            - Lyft
    registry:
        title: Registry

# Build settings
markdown: kramdown
permalink: pretty
