# Site settings
title: "Amanda & Matthew"
email: huastonewedding@gmail.com
url: amanda-and-matt.us
description: "March 24, 2018 | Cambridge, Massachusetts"

# Color settings (hex-codes without the leading hash-tag)
color:
  primary-dark: '#196980'
  primary-light: '#fff'
  links: '#d8dcd6'

# Footer settings
footer: Amanda and Matt

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: https://twitter.com/SBootstrap

# Build settings
markdown: kramdown
permalink: pretty
